version: "3.9"
   
services:
  db_tcom:
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
  api:
    image: app_tcom
    build: ./api
    command: bash -c "pwd && ls && python manage.py migrate && python manage.py runserver 0.0.0.0:${API_PORT}" #  --insecure
    volumes:
      - ./api:/code
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_NAME=${POSTGRES_SERVICE_NAME}
      - APP_NAME=Home
    depends_on:
      - db_tcom
  
  adminer:
    container_name: adminer_tcom
    image: dockette/adminer
    ports:
      - ${ADMINER_PORT}:80

