
CABINET_FACE = ( 
    ("AV", "AVANT"), 
    ("AR", "ARRIERE"), 
    ("GA", "GAUCHE"), 
    ("DR", "DROITE"), 
    ("TR", "TRAVERSE"), 
) 
CABINET_TYPE = ( 
    ("BAIE", "BAIE"), 
    ("FERME", "FERME") 
) 
CABLE_ALIM_TYPE = ( 
    ("1-1.5", "1x1,5mm²"), 
    ("1-2.5", "1x2,5mm²"), 
    ("3G2.5", "")  # à finir 
) 
CABLE_TYPE = ( 
    ("C", "CABLE"), 
    ("B", "BREAKOUT"), 
    ("J", "JARRETIERE"), 
    ("R", "CORDON RJ45") 
) 
CASSETTE_TYPE = ( 
    ("P", "PLATEAU DE LOVAGE BPE"), 
    ("E", "EPISSURE"),
    ("S", "SPLITTER"),
    ("C", "CONNECTEUR"),
)
CLIM_TYPE = ( 
    ("SANS", "SANS"), 
    ("VENTIL", "VENTILLATION"), 
    ("CLIM", "CLIMATISATION") 
) 
DOCUMENT_TYPE = ( 
    ("DIG", "DOSSIER D INGENIERIE : REGLES D INGENIERIE UTILISEES"), 
    ("ETU", "RAPPORT D ETUDE"), 
    ("PSI", "PLAN DE SITUATION, SYNOPTIQUE GEOGRAPHIQUE"), 
    ("PPH", "PLAN DE PHASAGE"), 
    ("PCB", "PLAN DE CABLAGE"), 
    ("PMQ", "PLAN DE MASQUE OU FICHE FOA"), 
    ("DPO", "DOSSIER APPUIS AERIENS"), 
    ("FOT", "PHOTO"), 
    ("PGC", "PLAN DE GENIE CIVIL"), 
    ("DLV", "DOSSIER DE LEVE OU D INVESTIGATIONS COMPLEMENTAIRES"), 
    ("SGC", "DETAIL OU SCHEMA DE GENIE CIVIL"), 
    ("DPI", "DOSSIER DE PIQUETAGE"), 
    ("DBL", "DOSSIER DE RELEVE BOITES AUX LETTRES"), 
    ("KRV", "REGLEMENT DE VOIRIE"), 
    ("CPV", "PERMISSION OU AUTORISATION DE VOIRIE"), 
    ("DTT", "DT EMISES DANS LE CADRE DU PROJET DE DEPLOIEMENT"), 
    ("DIT", "DICT EMISES DANS LE CADRE DU PROJET DE DEPLOIEMENT"), 
    ("DAM", "DIAGNOSTIC AMIANTE ENROBE"), 
    ("CIN", "CONTRAT OU CONVENTION DE LOCATION/CESSION/ACHAT/OCCUPATION D INFRASTRUCTURE"), 
    ("CMU", "CONTRAT OU CONVENTION DE CO-CONSTRUCTION OU MUTUALISATION DE TRAVAUX"), 
    ("DIP", "DOSSIER D IMPLANTATION (SRO, NRO, BPI…)"), 
    ("SOP", "SYNOPTIQUE OPTIQUE"), 
    ("SBP", "PLAN DE BOITE, OU AUTRE ELEMENT DE BRANCHEMENT PASSIF"), 
    ("SRA", "SCHEMA DE RACCORDEMENT (BAIE, ARMOIRE, REPARTITEUR…)"), 
    ("KEQ", "DOCUMENTATION TECHNIQUE D EQUIPEMENT"), 
    ("CIM", "CONVENTION THD IMMEUBLE"), 
    ("CIS", "CONVENTION CADRE BAILLEUR SOCIAL"), 
    ("CDS", "REGLEMENT DE SERVICE"), 
    ("COC", "AUTRE CONVENTION D OCCUPATION EMPRISE PRIVEE"), 
    ("MRF", "MESURE DE REFLECTOMETRIE"), 
    ("MFX", "TEST D ETANCHEITE DE FOURREAUX ET/OU TESTS DE MANDRINAGE, AIGUILLAGE"), 
    ("RGC", "PV DE RECEPTION GENIE CIVIL"), 
    ("DIF", "DOSSIER INFRASTRUCTURE D ACCUEIL"), 
    ("DCB", "DOSSIER DE CABLAGE"), 
    ("DOP", "DOSSIER OPTIQUE"), 
    ("DPR", "DOSSIER DE PROJET"), 
    ("DLG", "DOSSIER DE LIVRABLES GRACETHD"), 
    ("DCI", "DOSSIER DE COMMANDE POUR LOCATION/OCCUPATION D INFRASTRUCTURE"), 
    ("DCS", "DOSSIER DE CREATION DE SITE"), 
    ("DRS", "DOSSIER DE RACCORDEMENT DE SITE"), 
    ("KPL", "PLAN LOCAL D URBANISME"), 
    ("RFR", "FICHE DE RECETTE"), 
    ("RVR", "PV DE RECEPTION DE VOIRIE"), 
    ("DTA", "DIAGNOSTIC TECHNIQUE AMIANTE POUR UN IMMEUBLE") 
)
DRAWER_TYPE = ( 
    ("TIROIR", "TIROIR"), 
    ("TETE", "TETE DE CABLE") 
) 
EBP_LOGICAL_TYPE = ( 
    ("BPE", "BOITIER PROTECTION EPISSURE"), 
    ("PTO", "POINT DE TERMINAISON OPTIQUE"), 
    ("PBO", "POINT DE BRANCHEMENT OPTIQUE"),
    ("DTI", "DISPOSITIF DE TERMINAISON INTERIEUR OPTIQUE") 
) 
EBP_PHYSICAL_TYPE = ( 
    ("B006", "BPE 6FO"), 
    ("B012", "BPE 12FO"), 
    ("B024", "BPE 24FO"), 
    ("B036", "BPE 36FO"), 
    ("B048", "BPE 48FO"), 
    ("B072", "BPE 72FO"), 
    ("B096", "BPE 96FO"), 
    ("B144", "BPE 144FO"), 
    ("B288", "BPE 288FO"), 
    ("B432", "BPE 432FO"), 
    ("B576", "BPE 576FO"), 
    ("B720", "BPE 720FO"), 
    ("COF", "COFFRET"), 
    ("DTI1", "DTIO 1FO"), 
    ("DTI2", "DTIO 2FO"), 
    ("DTI4", "DTIO 4FO"), 
    ("AUTR", "AUTRE") 
) 
EQUIPMENT_TYPE = ( 
    ("SW", "SWITCH"), 
    ("RT", "ROUTEUR"), 
    ("WDM", "MUX WDM")
    # A COMPLETER
) 
FO_TYPE = ( 
    ("G651", "G651"), 
    ("G652", "G652"), 
    ("G652A", "G652A"), 
    ("G652B", "G652B"), 
    ("G652C", "G652C"), 
    ("G652D", "G652D"), 
    ("G653", "G653"), 
    ("G654", "G654"), 
    ("G655", "G655"), 
    ("G656", "G656"), 
    ("G657", "G657"), 
    ("G657A", "G657A"), 
    ("G657A1", "G657A1"), 
    ("G657A2", "G657A2"), 
    ("G657A3", "G657A3"), 
    ("G657B", "G657B"), 
    ("G657B1", "G657B1"), 
    ("G657B2", "G657B2"), 
    ("G657B3", "G657B3"), 
    ("OM1", "OM1"), 
    ("OM2", "OM2"), 
    ("OM3", "OM3"), 
    ("OM4", "OM4"), 
    ("OS1", "OS1"), 
    ("OS2", "OS2") 
) 
FO_COLOR = ( 
    ("1", "ROUGE (R)"), 
    ("2", "BLEU (BL)"), 
    ("3", "VERT (VE)"), 
    ("4", "JAUNE (J)"), 
    ("5", "VIOLET (V)"), 
    ("6", "BLANC (B)"), 
    ("7", "ORANGE (OR)"), 
    ("8", "GRIS (GR)"), 
    ("9", "MARRON (BR)"), 
    ("10", "NOIR (N)"), 
    ("11", "TURQUOISE (TU)"), 
    ("12", "ROSE (RS)"), 
    ("1.1", "BLEU (BL)"), 
    ("1.2", "ORANGE (OR)"), 
    ("1.3", "VERT (VE)"), 
    ("1.4", "MARRON (BR)"), 
    ("1.5", "GRIS (GR)"), 
    ("1.6", "BLANC (B)"), 
    ("1.7", "ROUGE (R)"), 
    ("1.8", "NOIR (N)"), 
    ("1.9", "VIOLET (V)"), 
    ("1.10", "JAUNE (J)"), 
    ("1.11", "ROSE (RS)"), 
    ("1.12", "TURQUOISE (TU)"), 
) 
INFRA_NATURE = ( 
    ("ASS", "ASSAINISSEMENT"), 
    ("EAU", "EAU"), 
    ("ELE", "ELECTRICITE"), 
    ("GAZ", "GAZ"), 
    ("NC", "NONCOMMUNIQUE"),  
    ("TEL", "TELECOM"), 
    ("HTZ", "HERTZIEN"), 
    ("CFT", "CHEMIN DE CÂBLE COURANT FORT"), 
    ("CFB", "CHEMIN DE CÂBLE COURANT FAIBLE"), 
) 
INFRA_LOGICAL_TYPE = ( 
    ("CX", "COLLECTE TRANSPORT DISTRIBUTION"), 
    ("CO", "COLLECTE"), 
    ("CT", "COLLECTE TRANSPORT"), 
    ("CD", "COLLECTE DISTRIBUTION"), 
    ("TD", "TRANSPORT DISTRIBUTION"), 
    ("TR", "TRANSPORT"), 
    ("DI", "DISTRIBUTION"), 
    ("RA", "RACCORDEMENT FINAL"), 
    ("BM", "BOUCLE METROPOLITAINE"), 
    ("LH", "LONGUE DISTANCE (LONG HAUL)"), 
    ("NC", "NON COMMUNIQUE"), 
    ("RO", "ROCADE"), 
) 
IMPLANTATION_TYPE = ( 
    ("0", "AERIEN TELECOM"), 
    ("1", "AERIEN ENERGIE"), 
    ("2", "FACADE"), 
    ("3", "IMMEUBLE"), 
    ("4", "PLEINE TERRE"), 
    ("5", "CANIVEAU"), 
    ("6", "GALERIE"), 
    ("7", "CONDUITE"), 
    ("8", "EGOUT"), 
    ("9", "SPECIFIQUE"), 
)     
INSTALLATION_METHOD = ( 
    ("NC", "NON COMMUNIQUE"), 
    ("TRA", "TRADITIONNELLE"), 
    ("MEC", "MECANISEE"), 
    ("MIC", "MICRO TRANCHEE"), 
    ("FOR", "FORAGE DIRIGE"), 
    ("ENS", "ENSOUILLAGE"), 
    ("FON", "FONÇAGE"), 
    ("ENC", "ENCORBELLEMENT"), 
    ("STU", "SOUS-TUBAGE"), 
) 
OCCUPATION_TYPE = ( 
    ("0", "VIDE"), 
    ("1.1", "NON VIDE EXPLOITABLE"), 
    ("1.2", "NON VIDE NON EXPLOITABLE"), 
    ("2", "SATUREE") 
) 
POSITION_FUNCTION = ( 
    ("CO", "CONNECTEUR"), 
    ("EP", "EPISSURE"), 
    ("PI", "PIGTAIL"), 
    ("AT", "ATTENTE"), 
    ("PA", "PASSAGE") 
) 
POSITION_TYPE = ( 
    ("CEA", "CONNECTEUR E2000-APC"), 
    ("CEU", "CONNECTEUR E2000-UPC"), 
    ("CEP", "CONNECTEUR E2000-PC"), 
    ("CFA", "CONNECTEUR FC-APC"), 
    ("CFU", "CONNECTEUR FC-UPC"), 
    ("CFP", "CONNECTEUR FC-PC"), 
    ("CLA", "CONNECTEUR LC-APC"), 
    ("CLU", "CONNECTEUR LC-UPC"), 
    ("CLP", "CONNECTEUR LC-PC"), 
    ("CMA", "CONNECTEUR MU-APC"), 
    ("CMU", "CONNECTEUR MU-UPC"), 
    ("CMP", "CONNECTEUR MU-PC"), 
    ("CSA", "CONNECTEUR SC-APC"), 
    ("CSU", "CONNECTEUR SC-UPC"), 
    ("CSP", "CONNECTEUR SC-PC"), 
    ("CTU", "CONNECTEUR ST-UPC"), 
    ("CTP", "CONNECTEUR ST-PC"), 
    ("CPO", "CONNECTEUR MT MPO"), 
    ("SFU", "SOUDURE FUSION"), 
    ("SME", "SOUDURE MECANIQUE") 
) 
PROPERTY_TYPE = ( 
    ("CST", "CONSTRUCTION"),
    ("RAC", "RACHAT"),
    ("CES", "CESSION"),
    ("IRU", "IRU"),
    ("LOC", "LOCATION"),
    ("OCC", "OCCUPATION"),
) 
REFERENCE_TYPE = ( 
    ("BA", "BAIE"), 
    ("BP", "BPE"), 
    ("CA", "CABLE"), 
    ("CR", "CARTE RESEAU"), 
    ("CS", "CASSETTE"), 
    ("DR", "DRAWER"), 
    ("EQ", "EQUIPEMENT"), 
    ("PT", "POINT TECHNIQUE"), 
    ("SW", "SWITCH"), 
    ("TI", "TIROIR"), 
    ("AU", "AUTRE") 
) 
SITE_LOGICAL_TYPE = ( 
    ("NRA", "NŒUD RACCORDEMENT D ABONNES"), 
    ("NRAHD", "NŒUD RACCORDEMENT D ABONNES - HAUT DEBIT"), 
    ("NRAMED", "NŒUD RACCORDEMENT D ABONNES - MONTEE EN DEBIT"), 
    ("NRAZO", "NŒUD RACCORDEMENT D ABONNES - ZONE D OMBRE"), 
    ("SRP", "SOUS-REPARTITEUR CUIVRE PRIMAIRE"), 
    ("SRS", "SOUS-REPARTITEUR CUIVRE SECONDAIRE"), 
    ("SRT", "SOUS-REPARTITEUR CUIVRE TERTIAIRE"), 
    ("NRO", "NŒUD RACCORDEMENT OPTIQUE"), 
    ("SRO", "SOUS-REPARTITEUR OPTIQUE"), 
    ("SROL", "SOUS-REPARTITEUR OPTIQUE COLOCALISE"), 
    ("BRASSAGE", "SITE DE BRASSAGE"), 
    ("CLIENT", "SITE CLIENT"), 
    ("HEBERG", "SITE HEBERGEMENT") 
) 
SITE_PHYSICAL_TYPE = ( 
    ("ADR", "ARMOIRE DE RUE"), 
    ("BAT", "BATIMENT"), 
    ("COF", "COFFRET"), 
    ("SHE", "SHELTER") 
) 
STATE_TYPE = ( 
    ("HS", "A CHANGER"), 
    ("ME", "MAUVAIS ETAT"), 
    ("OK", "BON ETAT"), 
    ("NC", "NON CONCERNE") 
) 
STATUS = ( 
    ("PRE", "ETUDE PRELIMINAIRE"), 
    ("DIA", "ETUDE DE DIAGNOSTIC"), 
    ("AVP", "AVANT-PROJET"), 
    ("PRO", "PROJET"), 
    ("ACT", "PASSATION DES MARCHES DE TRAVAUX"), 
    ("EXE", "ETUDE D EXECUTION"), 
    ("TVX", "TRAVAUX"), 
    ("REC", "RECOLEMENT"), 
    ("MCO", "MAINTIEN EN CONDITIONS OPERATIONNELLES")
) 
SUF_TYPE = ( 
    ('R', 'RESIDENTIEL'), 
    ('P', 'PROFESSIONNEL'), 
    ('O', 'OPERATEUR'), 
    ('T', 'TECHNIQUE'), 
) 
TECH_POINT_LOGICAL_TYPE = ( 
    ("T", "TIRAGE"), 
    ("R", "RACCORDEMENT"), 
    ("I", "INDETERMINE"),  
) 
TECH_POINT_NATURE = ( 
    ("A1", "CHAMBRE A1"), 
    ("A2", "CHAMBRE A2"), 
    ("A3", "CHAMBRE A3"), 
    ("A4", "CHAMBRE A4"), 
    ("A10", "CHAMBRE A10"), 
    ("A11", "CHAMBRE A11"), 
    ("A12", "CHAMBRE A12"), 
    ("A13", "CHAMBRE A13"), 
    ("A14", "CHAMBRE A14"), 
    ("A15", "CHAMBRE A15"), 
    ("A16", "CHAMBRE A16"), 
    ("A17", "CHAMBRE A17"), 
    ("A18", "CHAMBRE A18"), 
    ("B1", "CHAMBRE B1"), 
    ("B2", "CHAMBRE B2"), 
    ("B3", "CHAMBRE B3"), 
    ("B4", "CHAMBRE B4"), 
    ("C1", "CHAMBRE C1"), 
    ("C2", "CHAMBRE C2"), 
    ("C3", "CHAMBRE C3"), 
    ("C4", "CHAMBRE C4"), 
    ("D1", "CHAMBRE D1"), 
    ("D1C", "CHAMBRE D1C"), 
    ("D1T", "CHAMBRE D1T"), 
    ("D2", "CHAMBRE D2"), 
    ("D2C", "CHAMBRE D2C"), 
    ("D2T", "CHAMBRE D2T"), 
    ("D3", "CHAMBRE D3"), 
    ("D3C", "CHAMBRE D3C"), 
    ("D3T", "CHAMBRE D3T"), 
    ("D4", "CHAMBRE D4"), 
    ("D4C", "CHAMBRE D4C"), 
    ("D4T", "CHAMBRE D4T"), 
    ("D5", "CHAMBRE D5"), 
    ("D5C", "CHAMBRE D5C"), 
    ("D6", "CHAMBRE D6"), 
    ("D6C", "CHAMBRE D6C"), 
    ("D11", "CHAMBRE D11"), 
    ("D12", "CHAMBRE D12"), 
    ("D13", "CHAMBRE D13"), 
    ("D14", "CHAMBRE D14"), 
    ("E1", "CHAMBRE E1"), 
    ("E2", "CHAMBRE E2"), 
    ("E3", "CHAMBRE E3"), 
    ("E4", "CHAMBRE E4"), 
    ("J2C", "CHAMBRE J2C"), 
    ("J2CR", "CHAMBRE J2C REHAUSSEE"), 
    ("K1C", "CHAMBRE K1C"), 
    ("K1CR", "CHAMBRE K1C REHAUSSEE"), 
    ("K1T", "CHAMBRE K1T"), 
    ("K2C", "CHAMBRE K2C"), 
    ("K2CR", "CHAMBRE K2C REHAUSSEE"), 
    ("K2T", "CHAMBRE K2T"), 
    ("K3C", "CHAMBRE K3C"), 
    ("K3CR", "CHAMBRE K3C REHAUSSEE"), 
    ("K3T", "CHAMBRE K3T"), 
    ("L0T", "CHAMBRE L0T"), 
    ("L0TR", "CHAMBRE L0T REHAUSSEE"), 
    ("L1C", "CHAMBRE L1C"), 
    ("L1T", "CHAMBRE L1T"), 
    ("L1TR", "CHAMBRE L1T REHAUSSEE"), 
    ("L2C", "CHAMBRE L2C"), 
    ("L2T", "CHAMBRE L2T"), 
    ("L2TR", "CHAMBRE L2T REHAUSSEE"), 
    ("L3C", "CHAMBRE L3C"), 
    ("L3T", "CHAMBRE L3T"), 
    ("L3TR", "CHAMBRE L3T REHAUSSEE"), 
    ("L4C", "CHAMBRE L4C"), 
    ("L4T", "CHAMBRE L4T"), 
    ("L4TR", "CHAMBRE L4T REHAUSSEE"),  
    ("L5C", "CHAMBRE L5C"), 
    ("L5T", "CHAMBRE L5T"), 
    ("L5TR", "CHAMBRE L5T REHAUSSEE"), 
    ("L6T", "CHAMBRE L6T"), 
    ("L6TR", "CHAMBRE L6T REHAUSSEE"), 
    ("M1C", "CHAMBRE M1C"), 
    ("M1CR", "CHAMBRE M1C REHAUSSEE"), 
    ("M2T", "CHAMBRE M2T"), 
    ("M2TR", "CHAMBRE M2T REHAUSSEE"), 
    ("M3C", "CHAMBRE M3C"), 
    ("M3CR", "CHAMBRE M3C REHAUSSEE"), 
    ("P1C", "CHAMBRE P1C"), 
    ("P1CR", "CHAMBRE P1C REHAUSSEE"), 
    ("P1T", "CHAMBRE P1T"), 
    ("P1TR", "CHAMBRE P1T REHAUSSEE"), 
    ("P2C", "CHAMBRE P2C"), 
    ("P2CR", "CHAMBRE P2C REHAUSSEE"), 
    ("P2T", "CHAMBRE P2T"), 
    ("P2TR", "CHAMBRE P2T REHAUSSEE"), 
    ("P3C", "CHAMBRE P3C"), 
    ("P3T", "CHAMBRE P3T"), 
    ("P4C", "CHAMBRE P4C"), 
    ("P4T", "CHAMBRE P4T"), 
    ("P5C", "CHAMBRE P5C"), 
    ("P5T", "CHAMBRE P5T"), 
    ("P6C", "CHAMBRE P6C"), 
    ("P6T", "CHAMBRE P6T"), 
    ("R1T", "CHAMBRE R1T"), 
    ("R2T", "CHAMBRE R2T"), 
    ("R3T", "CHAMBRE R3T"), 
    ("S1", "CHAMBRE S1"), 
    ("S2", "CHAMBRE S2"), 
    ("S3", "CHAMBRE S3"), 
    ("S4", "CHAMBRE S4"), 
    ("S5", "CHAMBRE S5"), 
    ("S6", "CHAMBRE S6"), 
    ("S6bis", "CHAMBRE S6bis"), 
    ("S7", "CHAMBRE S7"), 
    ("TU1", "CHAMBRE TU1"), 
    ("TU2", "CHAMBRE TU2"), 
    ("TU4", "CHAMBRE TU4"), 
    ("TU6", "CHAMBRE TU6"), 
    ("TU8", "CHAMBRE TU8"), 
    ("TU10", "CHAMBRE TU10"), 
    ("OHN", "OUVRAGE HORS NORMES"), 
    ("PBOI", "POTEAU BOIS"), 
    ("PBET", "POTEAU BETON"), 
    ("PMET", "POTEAU METAL"), 
    ("PIND", "POTEAU INDETERMINE"), 
    ("POTL", "POTELET"), 
    ("BOU", "BOUCHON"), 
    ("REG", "REGARD 30X30"), 
    ("BAL", "BALCON"), 
    ("CRO", "CROCHET"), 
    ("FAI", "FAITIERE"), 
    ("STR", "SOUTERRAIN"), 
    ("SSO", "SOUS-SOL"), 
    ("TRA", "TRAVERSE"), 
    ("Y", "SITE MANCHONNAGE Y"), 
    ("IND", "INDETERMINE "), 
) 
TECH_POINT_PHYSICAL_TYPE = ( 
    ("A", "APPUI"), 
    ("C", "CHAMBRE"), 
    ("F", "ANCRAGE FACADE"), 
    ("I", "IMMEUBLE"), 
    ("Z", "AUTRE"), 
) 
TECHNOLOGY_TYPE = ( 
    ("CUT", "CUIVRE TELECOM"), 
    ("OPT", "OPTIQUE"), 
    ("COA", "COAXIAL"), 
    ("ECL", "ECLAIRAGE"), 
    ("ELE", "ELECTRICITE"), 
    ("VID", "VIDEO PROTECTION"), 
    ("RAD", "RADIO") 
) 
TUBE = (
    ("1", "SOUS FAISCEAU ROUGE UNE BAGUE COURTE"), 
    ("2", "SOUS FAISCEAU BLEU DEUX BAGUES COURTES"), 
    ("3", "SOUS FAISCEAU VERT TROIS BAGUES COURTES"), 
    ("4", "SOUS FAISCEAU JAUNE QUATRE BAGUES COURTES"), 
    ("5", "SOUS FAISCEAU VIOLET UNE BAGUE LONGUE"), 
    ("6", "SOUS FAISCEAU BLANC UNE BAGUE LONGUE ET UNE BAGUE COURTE"), 
    ("1.1", "ROUGE (R)"), 
    ("1.2", "BLEU (BL)"), 
    ("1.3", "VERT (VE)"), 
    ("1.4", "JAUNE (J)"), 
    ("1.5", "VIOLET (V)"), 
    ("1.6", "BLANC (B)"), 
    ("1.7", "ORANGE (OR)"), 
    ("1.8", "GRIS (GR)"), 
    ("1.9", "MARRON (BR)"), 
    ("1.10", "NOIR (N)"), 
    ("1.11", "TURQUOISE (TU)"), 
    ("1.12", "ROSE (RS)"), 
    ("1.13", "ROUGE (R) UNE BAGUE NOIRE"), 
    ("1.14", "BLEU (BL) UNE BAGUE NOIRE"), 
    ("1.15", "VERT (VE) UNE BAGUE NOIRE"), 
    ("1.16", "JAUNE (J) UNE BAGUE NOIRE"), 
    ("1.17", "VIOLET (V) UNE BAGUE NOIRE"), 
    ("1.18", "BLANC (B) UNE BAGUE NOIRE"), 
    ("1.19", "ORANGE (OR) UNE BAGUE NOIRE"), 
    ("1.20", "GRIS (GR) UNE BAGUE NOIRE"), 
    ("1.21", "MARRON (BR) UNE BAGUE NOIRE"), 
    ("1.22", "NOIR (N) UNE BAGUE NOIRE"), 
    ("1.23", "TURQUOISE (TU) UNE BAGUE NOIRE"), 
    ("1.24", "ROSE (RS) UNE BAGUE NOIRE"), 
    ("1.25", "ROUGE (R) DEUX BAGUES NOIRES"), 
    ("1.26", "BLEU (BL) DEUX BAGUES NOIRES"), 
    ("1.27", "VERT (VE) DEUX BAGUES NOIRES"), 
    ("1.28", "JADEUX (J) DEUX BAGUES NOIRES"), 
    ("1.29", "VIOLET (V) DEUX BAGUES NOIRES"), 
    ("1.30", "BLANC (B) DEUX BAGUES NOIRES"), 
    ("1.31", "ORANGE (OR) DEUX BAGUES NOIRES"), 
    ("1.32", "GRIS (GR) DEUX BAGUES NOIRES"), 
    ("1.33", "MARRON (BR) DEUX BAGUES NOIRES"), 
    ("1.34", "NOIR(N) DEUX BAGUES NOIRES"), 
    ("1.35", "TURQUOISE (TU) DEUX BAGUES NOIRES"), 
    ("1.36", "ROSE (RS) DEUX BAGUES NOIRES"), 
    ("1.37", "ROUGE (R) TROIS BAGUES NOIRES"), 
    ("1.38", "BLEU (BL) TROIS BAGUES NOIRES"), 
    ("1.39", "VERT (VE) TROIS BAGUES NOIRES"), 
    ("1.40", "JATROIS (J) TROIS BAGUES NOIRES"), 
    ("1.41", "VIOLET (V) TROIS BAGUES NOIRES"), 
    ("1.42", "BLANC (B) TROIS BAGUES NOIRES"), 
    ("1.43", "ORANGE (OR) TROIS BAGUES NOIRES"), 
    ("1.44", "GRIS (GR) TROIS BAGUES NOIRES"), 
    ("1.45", "MARRON (BR) TROIS BAGUES NOIRES"), 
    ("1.46", "NOIR (N) TROIS BAGUES NOIRES"), 
    ("1.47", "TURQUOISE (TU) TROIS BAGUES NOIRES"), 
    ("1.48", "ROSE (RS) TROIS BAGUES NOIRES"), 
    ("1.49", "ROUGE (R) QUATRE BAGUES NOIRES"), 
    ("1.50", "BLEU (BL) QUATRE BAGUES NOIRES"), 
    ("1.51", "VERT (VE) QUATRE BAGUES NOIRES"), 
    ("1.52", "JAQUATRE (J) QUATRE BAGUES NOIRES"), 
    ("1.53", "VIOLET (V) QUATRE BAGUES NOIRES"), 
    ("1.54", "BLANC (B) QUATRE BAGUES NOIRES"), 
    ("1.55", "ORANGE (OR) QUATRE BAGUES NOIRES"), 
    ("1.56", "GRIS (GR) QUATRE BAGUES NOIRES"), 
    ("1.57", "MARRON (BR) QUATRE BAGUES NOIRES"), 
    ("1.58", "NOIR (N) QUATRE BAGUES NOIRES"), 
    ("1.59", "TURQUOISE (TU) QUATRE BAGUES NOIRES"), 
    ("1.60", "ROSE (RS) QUATRE BAGUES NOIRES"), 
    ("1.61", "ROUGE (R) CINQ BAGUES NOIRES"), 
    ("1.62", "BLEU (BL) CINQ BAGUES NOIRES"), 
    ("1.63", "VERT (VE) CINQ BAGUES NOIRES"), 
    ("1.64", "JACINQ (J) CINQ BAGUES NOIRES"), 
    ("1.65", "VIOLET (V) CINQ BAGUES NOIRES"), 
    ("1.66", "BLANC (B) CINQ BAGUES NOIRES"), 
    ("1.67", "ORANGE (OR) CINQ BAGUES NOIRES"), 
    ("1.68", "GRIS (GR) CINQ BAGUES NOIRES"), 
    ("1.69", "MARRON (BR) CINQ BAGUES NOIRES"), 
    ("1.70", "NOIR (N) CINQ BAGUES NOIRES"), 
    ("1.71", "TURQUOISE (TU) CINQ BAGUES NOIRES"), 
    ("1.72", "ROSE (RS) CINQ BAGUES NOIRES"), 
) 
WAY_TYPE = ( 
    ("ACC", "ACCOTEMENT"), 
    ("CHAU", "CHAUSSEE"), 
    ("TROT", "TROTTOIR"), 
    ("TER", "TERRE"), 
    ("EMP", "EMPIERRE"), 
    ("PON", "PONT"), 
    ("SNC", "PASSAGE SNCF"), 
    ("CAN", "CANIVEAU TECHNIQUE"), 
    ("PAV", "PAVES"), 
    ("AQU", "AQUATIQUE"), 
    ("NC", "NON COMMUNIQUE"), 
)


