FROM python:3

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements.txt /code/

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN apt update && apt install nano 
RUN pip install -r requirements.txt

COPY . /code

